# Database settings
database:
  url: "mongodb://<user>:<password>@<server>:<port>/<dbname>?retryWrites=true&w=majority&authSource=admin"
  db: "<db>"
  timeout: 5

# Server settings
server:
  host: "<host>"
  port: "<:port>"
